#!/usr/bin/env python3

"""
Standard script to run GSurgeon
Author: Johannes Medagbe
Copyright (c) 2026
"""

import argparse
import asyncio
import os

import dspy
from Bio import Entrez
from dotenv import load_dotenv
from gsurgeon.operations.standard import operate

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--env-file", default=".env", help="Path to .env file")
    parser.add_argument("query", help="Question to answer")
    args = parser.parse_args()

    load_dotenv(dotenv_path=args.env_file)

    EMAIL = os.getenv("EMAIL")
    if EMAIL is None:
        raise ValueError("Set EMAIL for NCBI tool calling")
    Entrez.email = EMAIL

    MODEL_NAME = os.getenv("MODEL_NAME")
    if MODEL_NAME is None:
        raise ValueError("Set MODEL_NAME of a provider")

    API_KEY = os.getenv("API_KEY")
    if API_KEY is None:
        raise ValueError("Set valid API_KEY for proprietary model")
    model = dspy.LM(
        MODEL_NAME,
        api_key=API_KEY,
        max_tokens=20_000,
        temperature=0,
        verbose=False,
    )

    dspy.configure(lm=model)

    N_STEPS = os.getenv("N_STEPS")
    if N_STEPS is None:
        raise ValueError("Set N_STEPS for operation")
    n_steps = int(N_STEPS)

    print(asyncio.run(operate(args.query, n_steps)))
