[project]
name = "gsurgeon"
version = "0.1.0"
description = "A tool to dissect biology of model organisms using genomic information"
authors = [
    {name = "Johannes Medagbe",email = "johanmedagbe@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-core (>=1.4.0,<2.0.0)",
    "langgraph (>=1.2.0,<2.0.0)"
]

[project.urls]
Homepage = "https://github.com/johanmed/gsurgeon"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
